apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: dashboard 
spec:
  type: ClusterIP
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  